### ISSUE TITLE
Improve Mobile Responsiveness for Smaller Screens

### ISSUE THREAD

**Issue by OleksandrZadvornyi** [OleksandrZadvornyi/educate-landing#1]
## Summary
Improve mobile responsiveness for smaller screens by adjusting layout and styling elements to ensure optimal user experience on devices with smaller screen sizes.

### Basic example
Adjust the current CSS media queries to support a wider range of small devices (e.g., smartphones with screen widths under 375px). Ensure elements like text, images, and buttons scale appropriately and remain legible. For example:

```css
@media (max-width: 375px) {
  .container {
    padding: 10px;
  }
  .button {
    font-size: 14px;
    padding: 12px;
  }
}
```

### Motivation

This feature is aimed at improving the accessibility and usability of the website on smaller mobile devices. By ensuring that content scales correctly, users will have a smoother and more efficient browsing experience, ultimately increasing engagement and retention on mobile platforms.
